name: Check, Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install qemu-system
      run: sudo apt update && sudo apt install qemu-system -y 
    - name: Install libudev-dev
      run: sudo apt update && sudo apt install libudev-dev -y
    - name: Install toolchain
      run: rustup show
    - name: Check rust version
      run: rustc --version --verbose

    - uses: Swatinem/rust-cache@v2
      with:
          workspaces: "."

    - name: Install cargo-binutils
      run: cargo install cargo-binutils
    - name: Install ostool
      run: cargo install ostool
    - name: Add Target
      run: rustup target add aarch64-unknown-none
    - name: Check code format
      run: cargo fmt --all -- --check

    - uses: taiki-e/install-action@cargo-hack

    - name: Clippy for workspace
      run: cargo clippy --target aarch64-unknown-none -- -D warnings

    - name: Test
      run: cargo test -p hello --test test -- --show-output

   